INSERT INTO actors (id, name) VALUES
(1, 'John Doe'),
(2, 'Jane Smith'),
(3, 'Chris Evans'),
(4, 'Scarlett Johansson'),
(5, 'Robert Downey Jr.'),
(6, 'Tom Holland'),
(7, 'Mark Ruffalo'),
(8, 'Chris Hemsworth'),
(9, 'Natalie Portman'),
(10, 'Jeremy Renner'),
(11, 'Gal Gadot'),
(12, 'Jason Momoa'),
(13, 'Henry Cavill'),
(14, 'Ben Affleck'),
(15, 'Ezra Miller'),
(16, 'Ray Fisher'),
(17, 'Amber Heard'),
(18, 'Cillian Murphy'),
(19, 'Tom Hardy'),
(20, 'Anne Hathaway');
