spring:
  application:
    name: Bonfire Critic
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./DB
    username: admin
    password: admin
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      # change this in order to create the db from scratch or update
      ddl-auto: create
#            ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  tomcat:
    max-swallow-size: 100MB
